// <auto-generated />
namespace ScheduleIt2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Actual_Event_and_TimeOffEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Actual_Event_and_TimeOffEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201901021552206_Actual_Event_and_TimeOffEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
